### PR TITLE
Fix build tool version detection when symlinks is used

### PR DESCRIPTION
**Pull request by katyo**
Fix for #255

### CODE REVIEW

**Comment by Abdillah** [comment]
This all good in my NixOS machine @katyo  :+1:

**Comment by katyo** [comment]
@Abdillah nice!

**Comment by katyo** [comment]
Cargo apk looks like already unmaintained for now.

**Comment by Abdillah** [comment]
Yeah, I think so. With the new NDK, all the path screw up, especially with the new unified `llvm` toolchain. I am in the process of forking it, but might be for NixOS only.

**Comment by goddessfreya** [comment]
Didn't spot that this was tested. Thanks folks! Merging.

**Pull request merged**
