### PR TITLE
Remove injected glue

### PR DESCRIPTION
**Pull request by mb64**
This removes the injected-glue and replaces some of its functionality with a modified android_native_app_glue.c.  This is a very breaking change.

 * The stdout/stderr to Android log functionality is replaced with a C implementation in android_native_app_glue
 * The whole events on mpsc channels API is removed
 * glue now just provides a way to access the android_native_app_glue's `struct android_app*`
 * glue has [`android-ndk-sys`](https://github.com/mb64/android-ndk-rs) as a public dependency
 * As per [this comment](https://github.com/rust-windowing/winit/pull/1001#issuecomment-515770557), glue contains no NDK FFI or safe wrappers; they are in the `android-ndk` crate.

This change to the library also feels like a change to the philosophy of the library – from "an APK builder with a decent (but fixed) Rust interface" to "just an APK builder – bring your own NDK interactions".  As such I would appreciate feedback about what you see as this library's future, and if this is the right direction for it.

### CODE REVIEW

**Comment by philip-alldredge** [comment]
A couple thoughts:

- For future maintenance, it would be helpful to document how the `android_native_app_glue.c` was modified from the NDK version and which NDK version it was based on.
- I have slight concerns about `android-ndk-sys` and `cargo-apk` both defining the `android_app` struct. Having `glue` define the `cargo-apk` variant and then somehow convert between the two would potentially save debugging time down the road if `android_app` ever changed in either of them.  It has the benefit of triggering a compiler error if `android-ndk-sys` changed. However, that would mean we would have a third definition of `android_app`.  I'm likely overthinking things. It's no worse than we are right now.  The current build system doesn't vendor the `android_native_app_glue.c` and could have problems if that changed.

**Comment by philip-alldredge** [comment]
Is the intention for glue to be responsible for providing the android_app provided by `cargo-apk` or is it responsible for making an `android_app` as defined in `android-ndk-sys` available regardless of where it originated?

If it is the latter, then that clears up some of my confusion and resolves my concerns about `android-ndk-sys` defining as what I was viewing as the interface between `cargo-apk` and `glue`

Will glue expose any safe API for accessing the android_app? As it is, users of glue have no way of ensuring another library or thread isn't using or changing `android_app`. Unsafe code must be used to dereference the pointer but there isn't any practical way of knowing that there isn't a data race.

**Comment by mb64** [comment]
> it would be helpful to document how the android_native_app_glue.c was modified from the NDK version

Not that here is the right place to document it, but here are the changes:
 * It puts the `struct android_app *` in a global mutable static.  (This happens before any rust code is run, and never changes after, so it should be data-race free.)
 * It launches another thread that does the same thing as the injected-glue's logging thread (redirecting stdin/stdout to the Android log)
 * It runs `exit(0)` after onDestroy() – this is in hopes of exiting the app when main() exits, but doesn't work in all cases; I need to replace this with something better (probably involving `ANativeActivity_finish()` or the likes) 

> which NDK version it was based on

I have both r17c and r20 lying around on my computer; there is absolutely no difference between their android_native_app_glue versions. (Like `diff android-ndk-*/whatever` was empty.) But even looking at the version from [almost ten years ago](https://android.googlesource.com/platform/development/+/gingerbread/ndk/sources/android/native_app_glue/android_native_app_glue.h) the only differences are deprecation of `app_dummy()`, the log levels are different, and the `process_input` callback handles all input events instead of just the first one.

> Is the intention for glue to be responsible for providing the android_app provided by cargo-apk or is it responsible for making an android_app as defined in android-ndk-sys available regardless of where it originated?

The intention is that these are the same thing.  It hasn't changed for 10 years, and I don't expect it to change in the future.  If it does, though, I think cargo-apk should be updated to match it.

> Will glue expose any safe API for accessing the android_app?

This is a good question.  I don't want to put a safe API for working with android_native_app_glue into `android-ndk`, in case including it causes link errors when people don't use android_native_app_glue.  (I think android-ndk-sys is fine, because it contains essentially just headers, which won't cause any link troubles.)  If it makes sense to, I can see either of two possibilities for a safe API:

 * Another crate! `android_native_app_glue`, which exports types such as `AndroidApp`.  android_glue could have a function that returns an `AndroidApp`.
 * Put the safe API right into android_glue, don't bother with yet another crate.

**Comment by philip-alldredge** [comment]
Thanks for the explanation.

As you know, I think this is the right direction for things to move. This work and your winit 2.0 work are big steps in the right direction!

**Comment by mb64** [comment]
Thanks to #232, I moved the `native_app_glue` into the `android_glue` crate with a simple `build.rs` that uses the `cc` crate.  However, I'm currently figuring out issues whtere the `native_app_glue`'s `ANativeActivity_onCreate` doesn't get included in the final library.

**Comment by mb64** [comment]
I just force-pushed a newly-implemented rendition of this.

A feature I decided would be helpful is to be able to tell it to include the `injected-glue` anyway, using a `Cargo.toml` flag, so I included this as `package.metadata.android.use_legacy_glue`, defaulting to false.  It would be nicer to support a per-apk flag, but this required more restructuring, so I didn't include it for now.

**Comment by dvc94ch** [comment]
what's `use_legacy_glue` good for? Is this ready for merging?

**Pull request merged**
