### PR TITLE
Fixes building of crates containing inner attributes.

### LINKED ISSUE #229: Crates with inner attributes in root module no longer build
# The Problem
The build system merged in #223 fails to build crates which have inner attributes in the root module.

## Incomplete Example
```
// Inner attributes
#![no_std]
#![cfg_attr(
not(any(
    feature = "example_feature"
    )),
	allow(dead_code, unused_extern_crates, unused_imports)
)]

// macro_use attribute is only allowed at the crate root.
#[macro_use]
extern crate lazy_static;

mod child_mod;

fn main() {
	child_mod::do_something();
}
```

## References
- https://github.com/rust-lang/rfcs/issues/752
- https://github.com/rust-lang/rust/issues/47995
- https://github.com/rust-lang/rust/issues/18810		

**There is a proposed solution at the bottom of the issue. The following sections are included for discussion and documentation purposes.** 

# Things that don't work.
## Nested module with path attribute
For most uses of `include!`, this can be worked around by declaring an inner module and use the path attribute such at:

```
#[path="../real/main.rs"]
mod inner;
```

However, this solution is not feasible for our use case because:

- main is private and cannot be called
- Produces an error because `macro_use` is no longer at the crate root.
- Furthermore, although `no_std` will compile, it will produce a warning since it is not at the crate level.

## Embed main.rs into `lib.rs`
Simply moving the contents of the root module such as `main.rs` into `lib.rs` does not work. Since `lib.rs` is in a separate directory, it is unable to find any additional modules.

# Hacky Solution

- Read the `main.rs` and embed it in the generated `lib.rs`
- Extract troublesome statements like inner attributes and `macro_use` and move them to top level.  
- Add `pub` to `main`. 
- Add `path` attribute so that child modules will be resolved.

Example:

```
// Inner attributes
#![no_std]
#![cfg_attr(
not(any(
feature = "example_feature"
)),
	allow(dead_code, unused_extern_crates, unused_imports)
)]

// macro_use attribute is only allowed at the crate root.
#[macro_use]
extern crate lazy_static;

#[path="../real/"]
mod example {
    mod child_mod;

    // pub added to main
    pub fn main() {
        child_mod::do_something();
    }
}

use example::*;
```

# Proposed Solution - Create temporary file in user's source directory.
This solution is one I avoided experimenting with because it requires producing files outside of the `target` folder. However, it is the simplest. Because of is simplicity, it should be less fragile. I believe this solution should be implemented unless another one is proposed.

- Read root module such as `main.rs`
- Write it along with the current contents of cargo-apk's `lib.rs` to a temporary file in the same folder as `main.rs`. 
- Compile it.

Does anyone have thoughts about a better way to handle this case?
@mb64

### PR DESCRIPTION
**Pull request by philip-alldredge**
Creates a temporary file along side the crate root rather than using "lib.rs" in the target directory.
Temporary file contains the user's crate root source file as well as the `android_main`
Added test to ensure build crates with inner attributes work.

Closes #229

### CODE REVIEW

**Comment by philip-alldredge** [comment]
@mb64 this does what was mentioned in #229. I avoided using the `tempfile` crate because it doesn't allow specifying the complete file path of the temporary file. Since we are creating it in the user's source directory, I wanted to ensure files had a predictable name. Files not being deleted shouldn't be a problem However, if there is a problem, the user at least knows who to blame.

**Comment by mb64** [comment]
I hadn't heard of the `tempfile` crate, but looking at its docs, it seems like it should be possible with something like

```rust
let file = tempfile::Builder::new()
    .suffix(".rs")
    .tempfile_in(src_dir)?;
write!(file, ...)?;
let path = file.into_temp_path();
do_cargo_suff_with(&path);
// When path is dropped, the file will be deleted
```

**Comment by philip-alldredge** [comment]
Pushed a new version which uses the `tempfile` crate.

**Comment by philip-alldredge** [comment]
@mb64 after additional usage, I think it would be best not use the `tempfile` crate. It is not that unusual to forcefully terminate a build. In such cases named temporary files are not removed. The previous method would have the same issue but it would be trivial to ensure that it would overwrite and thus drop the file during the next build.

**Comment by philip-alldredge** [comment]
@mb64 I have reverted the usage of the `tempfile` crate for the reasons described and confirmed that the previous implementation works in way that IMHO is better in this scenario. In the event of a lingering temporary file, it will be removed during the next build. Recommend merging unless you have concerns. Squashing would be best to avoid all the commit noise.

**Comment by mb64** [comment]
Sorry for my slow response -- I'm pretty busy right now, and haven't had much time to work on this.

The implementation LGTM, but before I merge it, I'd like to see an update to the "how it works" section of the readme that mentions the temporary file.  A couple of other UI features that would be nice (but I'm fine without, in the interest of not blocking other progress) are:
 * Explaining the issue if the source directory is not writable
 * Printing a warning when the temp file is there at the start of compilation (maybe not though)

**Comment by philip-alldredge** [comment]
Pushed an updated README and improved error message.

**Pull request merged**
