### PR TITLE
Fix asset subdirectory loading issue

### PR DESCRIPTION
**Pull request by philip-alldredge**
Switch to only using aapt instead of aapt2 to work around assets folder on windows. Caused by aapt2 issue: https://issuetracker.google.com/issues/120436372

### CODE REVIEW

**Comment by philip-alldredge** [comment]
Closes #243

**Comment by mb64** [comment]
I'm not familiar with aapt vs aapt2 – is there any reason to prefer aapt2 over aapt?  Would it be worth switching back to aapt2 once the issue is fixed?

**Comment by philip-alldredge** [comment]
I'm not too familiar with the benefits of aapt2 over aapt. I'm not aware of any major benefits for cargo-apk to use aapt2. 

Previously we were using a mixture of aapt and aapt2 because of difficulties implementing everything using just aapt2. Of course we would need to switch to aapt2 if google ever deprecated aapt.

**Comment by mb64** [comment]
CI failed, but it's only the key creation race condition in the test code, so I'll merge.

**Pull request merged**
